baseURL = 'http://localhost:1313/'
languageCode = 'zh-cn'
title = '木山木山的小站'
theme = 'mushan'

[pagination]
pagerSize = 10

[markup.postCSS]
use = ["postcss"]
includePaths = ["assets/css"]

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Post"
url = "/post/"
weight = 2


[[menu.main]]
name = "Draw"
url = "/draw/"
weight = 3

[[menu.main]]
name = "Read"
url = "/read/"
weight = 4

[[menu.main]]
name = "Profile"
url = "/profile/"
weight = 5


[params]
author = "木山木山"
